/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Level = IDL.Variant({
  'one' : IDL.Null,
  'two' : IDL.Null,
  'three' : IDL.Null,
  'five' : IDL.Null,
  'four' : IDL.Null,
});
export const Position = IDL.Variant({ 'drive' : IDL.Null, 'reves' : IDL.Null });
export const Zone = IDL.Text;
export const Filters = IDL.Record({
  'levelMax' : Level,
  'levelMin' : Level,
  'zone' : IDL.Text,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'wins' : IDL.Nat,
  'zone' : Zone,
  'level' : Level,
  'availability' : IDL.Vec(IDL.Text),
  'matchesPlayed' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'position' : Position,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Match = IDL.Record({
  'createdAt' : Time,
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, Level, Position, Zone, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'discoverCandidates' : IDL.Func([Filters], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChat' : IDL.Func([IDL.Principal], [IDL.Vec(ChatMessage)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getOwnProfile' : IDL.Func([], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, Level, Position, Zone, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Level = IDL.Variant({
    'one' : IDL.Null,
    'two' : IDL.Null,
    'three' : IDL.Null,
    'five' : IDL.Null,
    'four' : IDL.Null,
  });
  const Position = IDL.Variant({ 'drive' : IDL.Null, 'reves' : IDL.Null });
  const Zone = IDL.Text;
  const Filters = IDL.Record({
    'levelMax' : Level,
    'levelMin' : Level,
    'zone' : IDL.Text,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'wins' : IDL.Nat,
    'zone' : Zone,
    'level' : Level,
    'availability' : IDL.Vec(IDL.Text),
    'matchesPlayed' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'position' : Position,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Match = IDL.Record({
    'createdAt' : Time,
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, Level, Position, Zone, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'discoverCandidates' : IDL.Func([Filters], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChat' : IDL.Func([IDL.Principal], [IDL.Vec(ChatMessage)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getOwnProfile' : IDL.Func([], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, Level, Position, Zone, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };