/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'fifth' : IDL.Null,
  'first' : IDL.Null,
  'third' : IDL.Null,
  'seventh' : IDL.Null,
  'second' : IDL.Null,
  'sixth' : IDL.Null,
  'fourth' : IDL.Null,
});
export const Position = IDL.Variant({ 'drive' : IDL.Null, 'reves' : IDL.Null });
export const Zone = IDL.Text;
export const Filters = IDL.Variant({
  'zone' : IDL.Null,
  'category' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'zone' : Zone,
  'created_at' : Time,
  'availability' : IDL.Vec(IDL.Text),
  'category' : Category,
  'matchesPlayed' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'position' : Position,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        Category,
        Position,
        Zone,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'discoverCandidates' : IDL.Func([Filters], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        Category,
        Position,
        Zone,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'fifth' : IDL.Null,
    'first' : IDL.Null,
    'third' : IDL.Null,
    'seventh' : IDL.Null,
    'second' : IDL.Null,
    'sixth' : IDL.Null,
    'fourth' : IDL.Null,
  });
  const Position = IDL.Variant({ 'drive' : IDL.Null, 'reves' : IDL.Null });
  const Zone = IDL.Text;
  const Filters = IDL.Variant({ 'zone' : IDL.Null, 'category' : IDL.Null });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'zone' : Zone,
    'created_at' : Time,
    'availability' : IDL.Vec(IDL.Text),
    'category' : Category,
    'matchesPlayed' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'position' : Position,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          Category,
          Position,
          Zone,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'discoverCandidates' : IDL.Func([Filters], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          Category,
          Position,
          Zone,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };